### ISSUE TITLE
Module not working with PF2e 3.3.0

### ISSUE THREAD

**Issue by leerhund** [jamespdaily/pf2e-sheet-skill-actions#14]
When you click one of the buttons to roll, nothing shows in chat.
This error is from Intimidate: Demoralize
![image](https://user-images.githubusercontent.com/95336883/151663382-86c89302-aa22-40c6-898e-86120eb64ec2.png)

**Comment by jamespdaily** [comment]
Thanks for catching this! I'll take a look ASAP and get a fix in
