### ISSUE TITLE
[Request] Option to move skill actions to bottom of sheet

### ISSUE THREAD

**Issue by Spappz** [jamespdaily/pf2e-sheet-skill-actions#37]
Currently, 'custom' actions (and reactions + free actions) are displayed below the skill actions added by this module. Since there are _many_ skill actions, most of which are far less used than these 'custom' actions granted by ancestry/class/etc., I think it would be useful to move skill actions below them. This way you don't need to scroll for as long, which perhaps saves me a couple of muscle tugs!

**Comment by jamespdaily** [comment]
Appreciate the phrase "muscle tugs"

**Comment by Spappz** [comment]
Implemented by #44
