### ISSUE TITLE
Feature Request: More Actions

### ISSUE THREAD

**Issue by shandrakor** [jamespdaily/pf2e-sheet-skill-actions#5]
I notice that the actions included in the module are limited to just the most combat-focused of the options. There's plenty of other skill actions that PCs might regularly roll...balance, climb, sneak, swim, tumble through, and so on. I suspect your goal was to not clutter things up...maybe have a dividing line putting the combat actions at the top, a separator and then the movement ones, and maybe more misc at the bottom? Down the line you could even have a simple options menu to display or not particular categories of actions.

**Comment by jamespdaily** [comment]
You got it, I was attempting to not clutter up the screen.  However I totally agree, I'd love to get these additional actions in to the character sheet.  

I GM for groups of players new to PF2e so coaxing Foundry to not get in the way of the players learning to play the game is a constant goal of mine with my modules, skill actions being currently a pretty big pain point for new players since they don't operate like everything else without this module.

I like your idea of having another separator and I might do that in the short term and aim for a toggleable sub-menu for the various skill action categories as it gets closer to 1.0

**Comment by andriusch** [comment]
What if you were allowed to "unequip" actions same as in strikes. So you could click the t-shirt button to essentially hide an action and you would have brown t-shirt button to toggle showing hidden actions?

**Comment by jamespdaily** [comment]
That's also a good idea. I'd still need a sub-menu of some sort so that the "un-equipped" actions could be re-equipped but should take out some of the headache and guesswork in trying to determine if a character has the proper skills and feats to show or hide a skill action

**Comment by andriusch** [comment]
I mean something like this:
![image](https://user-images.githubusercontent.com/25230/149214217-d1376750-987a-400a-b5d4-4366e27c9b1b.png)

So you could click the t-shirt button to hide "unequipped" actions or click it again to show them and unhide them if needed.

**Comment by jocolamarco** [comment]
Not sure if it's the right place but is there a list of what actions are currently handled?

**Comment by jamespdaily** [comment]
Yep! You can actually check the bottom of the code I linked below, it's just a manual entry of skills I've included.  Very simple to add more in.

I've been out of town for a bit and won't be back for another week or two so I won't be able to get to any of these major changes for a bit but looking forward to gettting these issues resolved


https://github.com/jamespdaily/pf2e-sheet-skill-actions/blob/master/src/module/sheet-skill-actions.ts

**Comment by Unikatze** [comment]
I'd suggest adding actions to the Exploration Tab. 
Things like Climb, Sneak and such could be added there. 
Others that are exploration only, like Coerce, Make an Impression, Gather Information, etc. 
Some may be even possible to be added to the Downtime Tab.

**Comment by jamespdaily** [comment]
I like the idea, shouldnt be hard to add!

**Comment by jamespdaily** [comment]
I believe we have everything at this point, yeah? Going to close this one
