### ISSUE TITLE
Skill actions not displaying on sheet

### ISSUE THREAD

**Issue by Spappz** [jamespdaily/pf2e-sheet-skill-actions#56]
As the title says, after updating my `pf2e` system to v3.11.0.3, the skill actions added by this module—including the header for it—are vacant from the character sheet.
<img src="https://user-images.githubusercontent.com/34202141/173396343-3c502750-3619-4a84-8027-73067e727140.png" width="60%" />

The following error message appears upon opening a character sheet:
![image](https://user-images.githubusercontent.com/34202141/173396835-56a4a89a-c3d4-4167-86ff-ae42166651a0.png)

Tested in a fresh world with no other modules activated.
Foundry version 9.269
`pf2e` system version 3.11.0.3
`pf2e-sheet-skill-actions` module version 1.2.0

**Comment by Glunty** [comment]
Compatibility problem with 3.11

System has changed an API on ItemPF2e : https://github.com/foundryvtt/pf2e/commit/29f43d450410586163d40ed3aacb9e2fb2122261
That causes us problem here : https://github.com/jamespdaily/pf2e-sheet-skill-actions/blob/94ffbb9e8e3c2cf810a6e7cc6ca0db698dee44ed/src/module/skill-actions.ts#L187

I should be able to fix that this weekend if nobody can before
