### ISSUE TITLE
Skill checks roll for selected token, not from actor sheet

### ISSUE THREAD

**Issue by jamespdaily** [jamespdaily/pf2e-sheet-skill-actions#7]
Skills should roll from the actor sheet, not the selected token

**Comment by Glunty** [comment]
It's PF2E code that rules it, you don't have control over who rolls when you call game.pf2e.actions.XXX 

actions.ts:186, we have that logic : 

        if (multiple actors selected) {
            roll for all actors
        } else if (one actor selected) {
            roll for selected one
        } else if (user has one or more controlled tokens on the canvas (familiars,...)) {
            roll for all controlled tokens
        } else if (user is a player character) {
            roll for character actor
        }

Perhaps we can challenge that logic, but it would impact system macros and others places those actions are called from.
